config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users

  resources :ebikes, only: %w[index new show create destroy update] do
    # resources :bookings, only: %w[index show new create delete update]
    resources :bookings, only: %w[new create]
  end
  # test to see what
  resources :bookings, only: %w[index destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :ebike
  belongs_to :user
end

app/models/ebike.rb
class Ebike < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ebikes
  has_many :bookings

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/ebikes_controller.rb
class EbikesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show index]

  def index
    @ebike = Ebike.all

    # add geocoder here
  end

  def show
    @ebike = Ebike.find(params[:id])
    @booking = Booking.new

  end

  def new
    @ebike = Ebike.new
  end

  def create
    @ebike = Ebike.new(ebike_params.merge(user_id: current_user.id))
     if @ebike.save!
      redirect_to @ebike
    else
      render :new
    end
  end

  def update
    @ebike = Ebike.find(params[:id])
    @ebike.update()
  end

  def destroy
  end

  private

  def ebike_params
    params.require(:ebike).permit(:name, :cost, :description, :location, :rating)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ebikes/_bookings_form.html.erb
<%= simple_form_for [@ebike, @booking] do |f| %>
  <div class="form-inputs">
    <%= f.input :booking_start_date, as: :date, html5: true, label_html: {class: 'booking-label' }, input_html: { class: "booking-btn"} %>
    <%= f.input :booking_end_date, as: :date, html5: true,label_html: {class: 'booking-label' }, input_html: { class: "booking-btn"} %>
  </div>
  <div class="price-calculator" style="color: white">
    <p id="price">Price per Day: £<span id="price-per-day"><%= @ebike.cost %></span></p>
    <hr>
    <p id="total-price">Total: £0</p>
  </div>
  <div class="form-actions">
    <%= f.button :submit, { class: "booking-btn mt-0", value: "Create Booking" } %>
  </div>
<% end %>

app/views/ebikes/_form.html.erb
<div class="fg-container">

  <%= simple_form_for(@ebike) do |f| %>
    <div class="fg-form">
      <%= f.input :name, placeholder:'Equipment Name'%>
      <%= f.input :cost, placeholder:'Cost' %>
      <%= f.input :location, placeholder:'Location' %>
      <%= f.input :description , placeholder:'Description'%>
      <%= f.input :photo, as: :file %>
      <%= f.button :submit, class: "cta-btn" %>
    </div>
  <% end %>

</div>

app/views/ebikes/index.html.erb
<div class="container">
  <h1>EBIKES</h1>
  <div class="index-body">
    <div class="cards">
      <% @ebike.each do |ebike| %>
        <div class="card mb-3">
          <div class="card-image">
            <!-- #empty for now -->
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= ebike.name %></h5>
            <p class="card-text"><%= ebike.description.truncate(50) %></p>
            <div class="link-and-price">
              <p class="card-link"><%= link_to "Step inside", ebike_path(ebike) %></p>
              <p class="card-price">£<%= ebike.cost %></p>
            </div>

          </div>
        </div>

      <% end %>
    </div>

  </div>
</div>

app/views/ebikes/new.html.erb
<div class="body-page">
  <h1> Add Equipment</h1>

  <%= render 'form', ebike: @ebike %>
  <br>
  <br>
</div>

app/views/ebikes/show.html.erb
<div id="show_page">
  <div class="header_and_photos">
    <div class="header_and_location">
      <div class="header">
        <h3><%= @ebike.name.upcase %></h3>
      </div>
      <div class="location">
        <p><i class="fas fa-star"></i> <%= @ebike.rating %> | superhost <i class="fas fa-heart"></i> |  <%= @ebike.location %> | <i class="fas fa-wifi"></i>   <i class="fas fa-space-shuttle"></i></p>
      </div>
    </div>
    <div class="photo_and_bookings">
      <div class="photo">

      </div>
      <div class="bookings-form">
        <%= render "bookings_form" %>

      </div>
    </div>
    <hr class="hr">
    <div class=showpage-btn-container>
      <% if current_user && current_user.ebike.include?(@ebike) %>
        <%= link_to 'Edit', edit_ebike_path, class: 'edit-delete-btn' %>

        <%= link_to "Delete",ebike_path(@ebike), class: 'edit-delete-btn',
          method: :delete,
          data: { confirm: "Are you sure?" } %>
      <% end %>
    </div>
    <div class="show_info">
      <p class="show_card_text"><strong><%= @ebike.name.upcase %></strong></p>
      <p class="show_card_text">Price: £<%= @ebike.cost %>/day</p>
      <br>
      <p class="text">Description: <%= @ebike.description %></p>
      <br>
    </div>
    <div class="">
    </div>
  </div>
</div>

<%= javascript_pack_tag 'bookings_new' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentMyEbike</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>